# Generated by Django 2.1.7 on 2019-02-17 15:08

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='id',
            field=models.IntegerField(primary_key=builtins.id, serialize=False),
        ),
    ]
