# Generated by Django 2.1.7 on 2019-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20190217_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
