# Generated by Django 2.1.7 on 2019-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20190217_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesses',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
